### ISSUE TITLE
Migrate Q&A app from OpenAI to Aleph-Alpha

### ISSUE THREAD

**Issue by diego-apellaniz** [Aleph-Alpha/aleph-alpha-client#148]
Hello, I hope it is ok if I ask this here. I am testing if Aleph-Alpha can provide a similar quality of answers than OpenAI. We use their client to make queries to our project database.

First, I did a basic comparison test and the response times from Aleph-Alpha were significantly lower. So far. so good.

![image](https://github.com/Aleph-Alpha/aleph-alpha-client/assets/48953695/bb7bde48-c96c-47c3-a88c-24c452e2ee59)

Then I tried to use AA’s QaRequest class passing as argument just one of our one of our documents. The results were not so satisfying. The response time is higher and the answer is not so explanatory as I would like. Can I get better results? Is it possible to choose a certain model with the QaRequest class so the answer is a bit more detailed? Should I rather try to carry out a normal completion request sending the related text fragments as part of the instruction? How would the prompt string look like?

Aleph-Alpha QaRequest 

![image](https://github.com/Aleph-Alpha/aleph-alpha-client/assets/48953695/986e1c11-902d-47e1-8295-c1c9d272afd4)

Our App based on OpenAI’s gpt-3.5

![image](https://github.com/Aleph-Alpha/aleph-alpha-client/assets/48953695/a2b62b3d-eb33-4bcf-9baf-e041e17c62c8)

Thanks for your great work!

**Comment by benbrandt** [comment]
Hi @diego-apellaniz thanks for reaching out! And thanks for giving our technology a try :)

So, currently our QA endpoint's performance has some known issues, and I am not surprised to see the issue you have here. Since you aren't needing to chunk the document (you seem to have smaller chunks of text that you are asking questions about), it is doing some unnecessary steps that might be adding to your latency.

Given your use case you could try using some of our control models (`luminous-base-control`, `luminous-extended-control`, and `luminous-supreme-control`). To do so, you would use a prompt structured something like this:

```
### Instruction:
{{question}} If there's no answer, say NO_ANSWER_IN_TEXT. Only answer the question based on the text.

### Input:
{{input}}

### Response:
```

Where `{{question}}` would be your user query and `{{input}}` would be the part of your document.

Since your input looks to be all German, you can also try changing the Instruction to be in German as well:

```
{{question}} Wenn es keine Antwort gibt, gib {{no_answer_text}} aus. Beantworte die Frage nur anhand des Textes.
```

You should be able to try it with all three control models as well. `luminous-base-control` will return the answer the quickest, while `luminous-base-supreme` may have an increase in quality, depending on your use case, with `luminous-base-extended` somewhere in between.

We are hoping to release some more best practices for use cases like this in the near future, but hopefully this helps you get started.

If you do have larger documents that don't fit in the context length, or you want to have more precise answers to only portions of documents, you can also use a package I maintain called [semantic-text-splitter](https://pypi.org/project/semantic-text-splitter/) that allows you to chunk your documents, and you can pass it a `Tokenizer` generated from `client.tokenizer` for the model you have chosen.

Will close the ticket, but feel free to re-open if you have further questions. Thanks again!
